services:
  validator:
    image: ghcr.io/Sturdy-subnet/sturdy-subnet:latest
    container_name: sturdy-validator
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
      - "${AXON_PORT:-8001}:${API_PORT:-8001}"
    volumes:
      - .:/app
      - ~/.bittensor/wallets/:/root/.bittensor/wallets
    environment:
      - NETUID=${NETUID:-10}
      - NETWORK=${NETWORK:-wss://entrypoint-finney.opentensor.ai:443}
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - AXON_PORT=${API_PORT:-8001}
      - API_PORT=${API_PORT:-8000}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup --label-enable
